"""Signal generator — converts intel + market data into prioritised trade proposals.

Runs inside the MonitorService after each data refresh.  Produces
TradeProposal objects at three priority tiers:

  CRITICAL  — act within seconds (spikes, mass-liq reversals, wick scalps)
  DAILY     — valid for hours (momentum entries, trending setups, TV alignment)
  SWING     — limit-order plans valid for days with full entry/exit blueprints

Analytics feedback loop:
  The monitor feeds the latest AnalyticsSnapshot each tick.  The generator
  uses strategy weights, detected patterns, and modification suggestions to
  modulate proposal strength, skip losing combos, and boost outperformers.

The proposals are stored in HubState (in-memory) and delivered to bots
via the /internal/report HTTP response.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING

from loguru import logger

from shared.models import (
    AnalyticsSnapshot,
    EntryPlan,
    IntelSnapshot,
    SignalPriority,
    TradeProposal,
    TradeQueue,
    TrendingSnapshot,
)

if TYPE_CHECKING:
    from hub.candle_fetcher import CandleFetcher

MAJOR_SYMBOLS = {"BTC/USDT", "ETH/USDT", "SOL/USDT", "XRP/USDT", "DOGE/USDT", "ADA/USDT", "AVAX/USDT", "LINK/USDT"}

# Strategies generated by the signal generator don't map 1:1 to strategy names
# in the analytics DB.  This maps signal-generator strategy names to the bot
# strategies whose performance data is most relevant.
_STRATEGY_ANALYTICS_MAP: dict[str, str] = {
    "liq_reversal": "compound_momentum",
    "macro_spike": "market_open_volatility",
    "extreme_mover": "compound_momentum",
    "trending_momentum": "compound_momentum",
    "fear_accumulation": "swing_opportunity",
    "multi_intel_convergence": "compound_momentum",
    "major_momentum": "compound_momentum",
    "major_intel_direction": "compound_momentum",
    "overleveraged_fade": "mean_reversion",
    "capitulation_dip_buy": "swing_opportunity",
    "greed_reversal_plan": "swing_opportunity",
    "eth_rotation_play": "swing_opportunity",
    "major_swing": "swing_opportunity",
    "trending_filler": "compound_momentum",
    "major_filler": "compound_momentum",
}


class SignalGenerator:
    """Stateful generator that avoids duplicate proposals via cooldowns.

    Analytics-aware: reads strategy weights, patterns, and suggestions to
    continuously modulate signal strength.  Nothing is ever blocked — losing
    strategies just get progressively weaker signals until they're effectively
    below the bot's minimum threshold.
    """

    MIN_QUEUE_SIZE = 10
    _CEX_TREND_STRATEGIES = {
        "extreme_mover",
        "trending_momentum",
        "major_momentum",
        "multi_intel_convergence",
        "major_intel_direction",
        "major_swing",
        "trending_filler",
        "major_filler",
    }

    def __init__(self, preferred_market_type: str = "futures", major_symbols: set[str] | None = None) -> None:
        self._preferred_market_type = preferred_market_type
        self._major_symbols = major_symbols or MAJOR_SYMBOLS
        self._recent_ids: dict[str, datetime] = {}
        self._cooldown_seconds = {
            SignalPriority.CRITICAL: 30,
            SignalPriority.DAILY: 900,
            SignalPriority.SWING: 14400,
        }
        self._exchange_symbols: dict[str, set[str]] = {}  # {EXCHANGE: {symbols}}
        self._all_tradeable: set[str] = set()  # union of all exchange symbols

        # Rejection feedback — populated by monitor from HubState each tick.
        # Maps "symbol|strategy" → (reason, timestamp, consecutive_count).
        self._rejection_history: dict[str, tuple[str, datetime, int]] = {}
        self._rejection_base_cooldown = 300  # 5min base, doubles per consecutive rejection
        self._rejection_max_cooldown = 7200  # cap at 2 hours

        # Analytics feedback state (updated by monitor each tick)
        self._analytics: AnalyticsSnapshot | None = None
        self._strategy_weights: dict[str, float] = {}  # analytics engine weight per strategy
        self._strategy_streaks: dict[str, int] = {}  # current streak per strategy
        self._combo_penalties: dict[tuple[str, str], float] = {}  # (strategy, symbol) -> multiplier
        self._global_bad_regimes: set[str] = set()  # regimes with high loss rate (all strats)
        self._global_bad_hours: set[int] = set()  # hours with high loss rate (all strats)
        self._strat_bad_regimes: dict[str, set[str]] = {}  # per-strategy bad regimes
        self._strat_bad_hours: dict[str, set[int]] = {}  # per-strategy bad hours
        self._strat_weight_overrides: dict[str, float] = {}  # per-strategy multiplier from suggestions
        self._quick_trade_penalty: float = 1.0  # multiplier for scalp/quick proposals
        self._current_regime: str = "normal"  # set each generate() call
        self._current_hour: int = -1  # set each generate() call
        self._cex_symbol_state: dict[str, dict[str, float]] = {}
        self._openclaw_snapshot: IntelSnapshot | None = None

    # ------------------------------------------------------------------
    # Analytics feedback
    # ------------------------------------------------------------------

    def update_analytics(self, snap: AnalyticsSnapshot) -> None:
        """Ingest the latest analytics snapshot and rebuild lookup tables.

        Called by the monitor each tick.  Everything here becomes a soft
        strength multiplier — nothing is ever hard-blocked.
        """
        self._analytics = snap
        self._strategy_weights.clear()
        self._strategy_streaks.clear()
        self._combo_penalties.clear()
        self._global_bad_regimes.clear()
        self._global_bad_hours.clear()
        self._strat_bad_regimes.clear()
        self._strat_bad_hours.clear()
        self._strat_weight_overrides.clear()
        self._quick_trade_penalty = 1.0

        for w in snap.weights:
            self._strategy_weights[w.strategy] = w.weight
            self._strategy_streaks[w.strategy] = w.streak

        for pat in snap.patterns:
            ptype = pat.get("pattern_type", "")
            data = pat.get("data", {})

            if ptype == "market_regime":
                regime = data.get("regime", "")
                if regime:
                    self._global_bad_regimes.add(regime)

            elif ptype == "time_of_day":
                hour = data.get("hour")
                if hour is not None:
                    self._global_bad_hours.add(int(hour))

            elif ptype == "strategy_symbol":
                strat = pat.get("affected_strategy", "")
                sym = pat.get("affected_symbol", "")
                loss_rate = data.get("loss_rate", 0.0)
                if strat and sym and loss_rate > 0:
                    penalty = max(0.2, 1.0 - loss_rate)
                    self._combo_penalties[(strat, sym)] = penalty

            elif ptype == "quick_trade":
                loss_rate = data.get("loss_rate", 0.0)
                if loss_rate > 0.5:
                    self._quick_trade_penalty = max(0.3, 1.0 - loss_rate)

        for sug in snap.suggestions:
            stype = sug.get("suggestion_type", "")
            strat = sug.get("strategy", "")
            if not strat:
                continue
            analytics_strat = _STRATEGY_ANALYTICS_MAP.get(strat, strat)

            if stype == "regime_filter":
                val = sug.get("suggested_value", "")
                regime = val.replace("skip ", "").strip()
                if regime:
                    self._strat_bad_regimes.setdefault(analytics_strat, set()).add(regime)

            elif stype == "time_filter":
                val = sug.get("suggested_value", "")
                try:
                    hour = int(val.replace("skip hour ", "").strip())
                    self._strat_bad_hours.setdefault(analytics_strat, set()).add(hour)
                except (ValueError, TypeError):
                    pass
            elif stype == "disable":
                current = self._strat_weight_overrides.get(analytics_strat, 1.0)
                self._strat_weight_overrides[analytics_strat] = min(current, 0.3)
            elif stype in {"reduce_weight", "increase_weight", "weight_override"}:
                val = str(sug.get("suggested_value", "") or "").strip().lower()
                parsed = None
                if "=" in val:
                    with_value = val.split("=", 1)[1].strip()
                    try:
                        parsed = float(with_value)
                    except (TypeError, ValueError):
                        parsed = None
                if parsed is None:
                    try:
                        parsed = float(val)
                    except (TypeError, ValueError):
                        parsed = None
                if parsed is not None:
                    bounded = max(0.3, min(1.5, parsed))
                    current = self._strat_weight_overrides.get(analytics_strat, 1.0)
                    if stype == "reduce_weight":
                        self._strat_weight_overrides[analytics_strat] = min(current, bounded)
                    elif stype == "increase_weight":
                        self._strat_weight_overrides[analytics_strat] = max(current, bounded)
                    else:
                        self._strat_weight_overrides[analytics_strat] = bounded

        if snap.weights:
            logger.debug(
                "Analytics loaded: {} strategies, {} patterns, {} suggestions | global bad regimes={} bad hours={} overrides={}",
                len(snap.weights),
                len(snap.patterns),
                len(snap.suggestions),
                self._global_bad_regimes or "none",
                self._global_bad_hours or "none",
                self._strat_weight_overrides or "none",
            )

    def update_rejections(self, rejections: dict[str, tuple[str, datetime, int]]) -> None:
        """Ingest rejection history from HubState.

        Called by the monitor each tick. The signal generator uses this to
        apply escalating cooldowns on symbol+strategy combos that bots keep
        rejecting — breaks the propose→reject→propose loop.
        """
        self._rejection_history = rejections

    def _rejection_cooldown_active(self, symbol: str, strategy: str) -> bool:
        """Check if a symbol+strategy is on rejection cooldown."""
        rkey = f"{symbol}|{strategy}"
        entry = self._rejection_history.get(rkey)
        if not entry:
            return False
        _reason, ts, count = entry
        cooldown = min(self._rejection_base_cooldown * (2 ** (count - 1)), self._rejection_max_cooldown)
        elapsed = (datetime.now(UTC) - ts).total_seconds()
        if elapsed < cooldown:
            logger.debug(
                "Rejection cooldown active for {}|{} (rejected {}x, {}s remaining)",
                symbol,
                strategy,
                count,
                int(cooldown - elapsed),
            )
            return True
        return False

    def _analytics_strength_modifier(self, strategy: str, symbol: str, is_quick: bool = False) -> float:
        """Compute a strength multiplier from analytics feedback.

        Returns a value in [0.3, 1.5].  Never zero — nothing is blocked,
        just progressively de-prioritised as evidence accumulates against it.
        """
        if not self._analytics or not self._analytics.weights:
            return 1.0

        analytics_name = _STRATEGY_ANALYTICS_MAP.get(strategy, strategy)

        base_weight = self._strategy_weights.get(analytics_name, 1.0)
        modifier = base_weight

        streak = self._strategy_streaks.get(analytics_name, 0)
        if streak <= -5:
            modifier *= 0.5
        elif streak <= -3:
            modifier *= 0.7

        if self._current_regime in self._global_bad_regimes:
            modifier *= 0.7
        if self._current_regime in self._strat_bad_regimes.get(analytics_name, set()):
            modifier *= 0.6

        if self._current_hour in self._global_bad_hours:
            modifier *= 0.75
        if self._current_hour in self._strat_bad_hours.get(analytics_name, set()):
            modifier *= 0.6

        combo_key = (analytics_name, symbol)
        if combo_key in self._combo_penalties:
            modifier *= self._combo_penalties[combo_key]

        if analytics_name in self._strat_weight_overrides:
            modifier *= self._strat_weight_overrides[analytics_name]

        if is_quick and self._quick_trade_penalty < 1.0:
            modifier *= self._quick_trade_penalty

        return max(0.3, min(1.5, modifier))

    # ------------------------------------------------------------------
    # Exchange symbol tracking
    # ------------------------------------------------------------------

    def update_exchange_symbols(self, exchange_symbols: dict[str, set[str]]) -> None:
        """Update known exchange symbol sets (called by monitor each tick)."""
        self._exchange_symbols = exchange_symbols
        self._all_tradeable = set()
        for syms in exchange_symbols.values():
            self._all_tradeable |= syms

    def _symbol_tradeable(self, symbol: str) -> bool:
        """Check if at least one exchange supports this symbol."""
        if not self._all_tradeable:
            return False  # no exchange data yet — wait for bots to report
        return symbol in self._all_tradeable

    def _supported_exchanges(self, symbol: str) -> list[str]:
        """Return list of exchanges that have this symbol."""
        if not self._exchange_symbols:
            return []
        return [ex for ex, syms in self._exchange_symbols.items() if symbol in syms]

    def generate(self, snap: IntelSnapshot, queue: TradeQueue) -> TradeQueue:
        """Evaluate the current intel snapshot and append new proposals."""
        self._current_regime = snap.regime
        self._current_hour = datetime.now(UTC).hour
        self._cex_symbol_state = self._build_cex_symbol_state(snap)
        self._openclaw_snapshot = snap

        self._purge_cooldowns()
        queue.purge_stale()

        self._generate_critical(snap, queue)
        self._generate_daily(snap, queue)
        self._generate_swing(snap, queue)
        self._generate_filler(snap, queue)

        return queue

    # ------------------------------------------------------------------
    # CRITICAL — seconds to act
    # ------------------------------------------------------------------

    def _generate_critical(self, snap: IntelSnapshot, q: TradeQueue) -> None:
        # Mass liquidation reversal — contrarian entry on capitulation
        if snap.mass_liquidation:
            side = snap.liquidation_bias  # "long" when longs liquidated (buy dip)
            if side in ("long", "short"):
                self._propose(
                    q,
                    TradeProposal(
                        priority=SignalPriority.CRITICAL,
                        symbol="BTC/USDT",
                        side=side,
                        strategy="liq_reversal",
                        reason=f"Mass liq ${snap.liquidation_24h / 1e9:.1f}B — bias {side} (exhaustion reversal)",
                        strength=0.85,
                        leverage=10,
                        quick_trade=True,
                        max_hold_minutes=15,
                        max_age_seconds=120,
                        source="monitor",
                    ),
                )

        # Macro spike opportunity — FOMC/CPI just dropped, expect volatility
        if snap.macro_spike_opportunity:
            direction = snap.preferred_direction
            if direction in ("long", "short"):
                self._propose(
                    q,
                    TradeProposal(
                        priority=SignalPriority.CRITICAL,
                        symbol="BTC/USDT",
                        side=direction,
                        strategy="macro_spike",
                        reason=f"Macro event spike — {snap.next_macro_event}",
                        strength=0.75,
                        leverage=10,
                        quick_trade=True,
                        max_hold_minutes=10,
                        max_age_seconds=60,
                        source="monitor",
                    ),
                )

        # Hot mover with extreme 1h move — scalp the momentum
        for mover in snap.hot_movers[:5]:
            if abs(mover.change_1h) >= 8.0 and not mover.is_low_liquidity:
                side = "long" if mover.change_1h > 0 else "short"
                sym = self._pair_symbol(mover.symbol)
                self._propose(
                    q,
                    TradeProposal(
                        priority=SignalPriority.CRITICAL,
                        symbol=sym,
                        side=side,
                        strategy="extreme_mover",
                        reason=f"{mover.symbol} moved {mover.change_1h:+.1f}% in 1h",
                        strength=min(0.9, abs(mover.change_1h) / 12.0),
                        leverage=10,
                        quick_trade=True,
                        max_hold_minutes=10,
                        max_age_seconds=90,
                        source="monitor",
                    ),
                )

    # ------------------------------------------------------------------
    # DAILY — valid for hours
    # ------------------------------------------------------------------

    def _generate_daily(self, snap: IntelSnapshot, q: TradeQueue) -> None:
        # Trending coins with TV alignment — momentum entry
        tv_direction = snap.tv_btc_consensus
        for mover in self._merge_trending(snap):
            if mover.is_low_liquidity:
                continue
            if abs(mover.change_24h) < 2.0:
                continue

            side = "long" if mover.change_24h > 0 else "short"
            sym = self._pair_symbol(mover.symbol)

            tv_aligned = (tv_direction == side) or tv_direction == "neutral"
            strength = 0.40
            if abs(mover.change_24h) >= 5.0:
                strength += 0.10
            if tv_aligned:
                strength += 0.15
            if abs(mover.change_24h) > 10:
                strength += 0.10

            self._propose(
                q,
                TradeProposal(
                    priority=SignalPriority.DAILY,
                    symbol=sym,
                    side=side,
                    strategy="trending_momentum",
                    reason=f"{mover.symbol} 24h:{mover.change_24h:+.1f}% vol:${mover.volume_24h / 1e6:.0f}M"
                    f" TV:{tv_direction}",
                    strength=min(0.9, strength),
                    leverage=10,
                    max_age_seconds=14400,  # 4 hours
                    source="monitor",
                ),
            )

        # Fear zone BTC buy — accumulate when fearful
        if snap.fear_greed <= 30 and snap.preferred_direction == "long":
            self._propose(
                q,
                TradeProposal(
                    priority=SignalPriority.DAILY,
                    symbol="BTC/USDT",
                    side="long",
                    strategy="fear_accumulation",
                    reason=f"F&G={snap.fear_greed} (fear) — contrarian buy zone",
                    strength=0.65,
                    leverage=5,
                    max_age_seconds=7200,
                    source="monitor",
                ),
            )

        # Multiple intel sources agree on direction — high-conviction entry
        if snap.preferred_direction in ("long", "short"):
            aligned_sources = self._count_directional_agreement(snap)
            if aligned_sources >= 3:
                for sym in ("BTC/USDT", "ETH/USDT"):
                    self._propose(
                        q,
                        TradeProposal(
                            priority=SignalPriority.DAILY,
                            symbol=sym,
                            side=snap.preferred_direction,
                            strategy="multi_intel_convergence",
                            reason=f"{aligned_sources} intel sources agree: "
                            f"{snap.preferred_direction} (regime={snap.regime})",
                            strength=min(0.85, 0.5 + aligned_sources * 0.1),
                            leverage=10,
                            max_age_seconds=7200,
                            source="monitor",
                        ),
                    )

        # Major coins momentum — lower threshold than altcoins (2% vs 5%)
        for mover in self._merge_trending(snap):
            sym = self._pair_symbol(mover.symbol)
            if sym not in self._major_symbols:
                continue
            if abs(mover.change_24h) < 2.0:
                continue

            side = "long" if mover.change_24h > 0 else "short"
            strength = 0.50
            if tv_direction == side:
                strength += 0.15
            if abs(mover.change_24h) > 5:
                strength += 0.15
            if snap.fear_greed_bias == side:
                strength += 0.05

            self._propose(
                q,
                TradeProposal(
                    priority=SignalPriority.DAILY,
                    symbol=sym,
                    side=side,
                    strategy="major_momentum",
                    reason=f"{mover.symbol} 24h:{mover.change_24h:+.1f}% (major, lower threshold)",
                    strength=min(0.85, strength),
                    leverage=10,
                    max_age_seconds=14400,
                    source="monitor",
                ),
            )

        # Major coins intel-driven daily — propose when intel agrees even without big moves
        if snap.preferred_direction in ("long", "short"):
            for sym in self._major_symbols:
                self._propose(
                    q,
                    TradeProposal(
                        priority=SignalPriority.DAILY,
                        symbol=sym,
                        side=snap.preferred_direction,
                        strategy="major_intel_direction",
                        reason=f"Intel direction {snap.preferred_direction} for {sym} (regime={snap.regime})",
                        strength=0.45,
                        leverage=5,
                        max_age_seconds=7200,
                        source="monitor",
                    ),
                )

        # Overleveraged fade — contrarian against crowded positioning
        if snap.overleveraged_side in ("longs", "shorts"):
            fade_side = "short" if snap.overleveraged_side == "longs" else "long"
            self._propose(
                q,
                TradeProposal(
                    priority=SignalPriority.DAILY,
                    symbol="BTC/USDT",
                    side=fade_side,
                    strategy="overleveraged_fade",
                    reason=f"{snap.overleveraged_side} overleveraged — fade towards squeeze",
                    strength=0.55,
                    leverage=5,
                    max_age_seconds=14400,
                    source="monitor",
                ),
            )

    # ------------------------------------------------------------------
    # SWING — limit order plans with full entry blueprint
    # ------------------------------------------------------------------

    def _generate_swing(self, snap: IntelSnapshot, q: TradeQueue) -> None:
        # Extreme fear + heavy liquidations = "opportunity of a lifetime" candidate
        if snap.fear_greed <= 15 and snap.mass_liquidation:
            btc_tv = self._get_tv_analysis(snap, "BTC/USDT")
            rsi = btc_tv.rsi_14 if btc_tv else 30.0

            self._propose(
                q,
                TradeProposal(
                    priority=SignalPriority.SWING,
                    symbol="BTC/USDT",
                    side="long",
                    strategy="capitulation_dip_buy",
                    reason=f"Extreme fear ({snap.fear_greed}) + mass liq "
                    f"${snap.liquidation_24h / 1e9:.1f}B + RSI {rsi:.0f} — "
                    f"potential generational bottom",
                    strength=0.9,
                    leverage=10,
                    max_age_seconds=259200,  # 3 days
                    entry_plan=EntryPlan(
                        entry_zone_low=0,
                        entry_zone_high=0,
                        stop_loss=0,
                        take_profit_targets=[],
                        dca_levels=[],
                        initial_leverage=5,
                        max_leverage=10,
                        scale_in_pct=3.0,
                        notes="Capitulation event. PYRAMID mode: start small, DCA into "
                        "wicks, lever up on recovery. Add at -3%, -5%, -8%. "
                        "Move stop to break-even at +5%. Let it ride.",
                    ),
                    source="monitor",
                ),
            )

        # Caution regime + greed = short setup with planned entries
        if snap.regime in ("risk_off", "caution") and snap.fear_greed >= 70:
            self._propose(
                q,
                TradeProposal(
                    priority=SignalPriority.SWING,
                    symbol="BTC/USDT",
                    side="short",
                    strategy="greed_reversal_plan",
                    reason=f"Risk-off regime + F&G={snap.fear_greed} (greed) — planned short if momentum breaks",
                    strength=0.6,
                    leverage=5,
                    max_age_seconds=172800,  # 2 days
                    entry_plan=EntryPlan(
                        initial_leverage=5,
                        max_leverage=10,
                        scale_in_pct=2.0,
                        notes="Wait for momentum break (lower high on 4h). "
                        "Enter on confirmed rejection. Tight stop above "
                        "recent high. Take profit at fear zone (F&G < 40). "
                        "Trail 2% below each new lower high.",
                    ),
                    source="monitor",
                ),
            )

        # ETH swing when strong BTC + ETH lagging (rotation play)
        btc_tv = self._get_tv_analysis(snap, "BTC/USDT")
        eth_tv = self._get_tv_analysis(snap, "ETH/USDT")
        if btc_tv and eth_tv:
            btc_strong = btc_tv.consensus == "long"
            eth_weak = eth_tv.consensus in ("neutral", "short")
            if btc_strong and eth_weak and snap.fear_greed < 60:
                self._propose(
                    q,
                    TradeProposal(
                        priority=SignalPriority.SWING,
                        symbol="ETH/USDT",
                        side="long",
                        strategy="eth_rotation_play",
                        reason="BTC strong, ETH lagging — rotation play when ETH catches up",
                        strength=0.55,
                        leverage=5,
                        max_age_seconds=259200,
                        entry_plan=EntryPlan(
                            initial_leverage=3,
                            max_leverage=8,
                            scale_in_pct=2.0,
                            notes="Enter when ETH/BTC ratio starts turning up. "
                            "Use limit orders at recent support. "
                            "DCA if it dips further. Trail stop at 4%.",
                        ),
                        source="monitor",
                    ),
                )

        # Major coins structural swing — always keep the SWING queue populated
        # for majors based on broader market regime + technical confluence.
        self._generate_major_swings(snap, q)

    # ------------------------------------------------------------------
    # Major Coin Swing Proposals
    # ------------------------------------------------------------------

    def _generate_major_swings(self, snap: IntelSnapshot, q: TradeQueue) -> None:
        """Generate swing proposals for major coins based on regime + technicals.

        Unlike the altcoin trending loop, this runs for all major symbols on
        every cycle. Majors are steadier — they don't need 5%+ moves to be
        tradeable; regime alignment and technical confluence are enough.
        """
        direction = snap.preferred_direction
        if direction not in ("long", "short"):
            return

        regime_ok = (direction == "long" and snap.regime in ("risk_on", "normal")) or (
            direction == "short" and snap.regime in ("risk_off", "caution")
        )
        if not regime_ok:
            return

        aligned = self._count_directional_agreement(snap)
        if aligned < 2:
            return

        strength = 0.40 + aligned * 0.08
        fg = snap.fear_greed
        if (direction == "long" and fg <= 35) or (direction == "short" and fg >= 65):
            strength += 0.10

        for sym in self._major_symbols:
            tv = self._get_tv_analysis(snap, sym)
            sym_aligned = tv and tv.consensus == direction
            sym_strength = strength + (0.10 if sym_aligned else 0.0)

            self._propose(
                q,
                TradeProposal(
                    priority=SignalPriority.SWING,
                    symbol=sym,
                    side=direction,
                    strategy="major_swing",
                    reason=f"{sym} swing: {aligned} intel agree {direction}, regime={snap.regime}, F&G={fg}",
                    strength=min(0.85, sym_strength),
                    leverage=10,
                    max_age_seconds=172800,
                    entry_plan=EntryPlan(
                        initial_leverage=5,
                        max_leverage=10,
                        scale_in_pct=2.0,
                        notes=f"Major coin swing {direction}. Enter at support/resistance "
                        f"confirmation. DCA on dips. Trail stop 3-4%.",
                    ),
                    source="monitor",
                ),
            )

    # ------------------------------------------------------------------
    # Filler — keep queue populated with best-available opportunities
    # ------------------------------------------------------------------

    def _generate_filler(self, snap: IntelSnapshot, q: TradeQueue) -> None:
        """Ensure at least MIN_QUEUE_SIZE pending proposals exist.

        Runs after all other generators.  Picks the best trending coins
        that weren't already proposed, using lower strength values so
        bots can decide whether to act.
        """
        pending = q.pending_count
        if pending >= self.MIN_QUEUE_SIZE:
            return

        needed = self.MIN_QUEUE_SIZE - pending
        tv_direction = snap.tv_btc_consensus
        candidates = self._merge_trending(snap)
        candidates.sort(key=lambda m: abs(m.change_24h), reverse=True)

        existing_syms = {p.symbol for p in q.proposals if not p.is_expired}

        added = 0
        for mover in candidates:
            if added >= needed:
                break
            sym = self._pair_symbol(mover.symbol)
            if sym in existing_syms:
                continue
            if mover.is_low_liquidity:
                continue

            side = "long" if mover.change_24h > 0 else "short"
            strength = 0.30 + min(0.25, abs(mover.change_24h) / 40.0)
            if tv_direction == side:
                strength += 0.10

            self._propose(
                q,
                TradeProposal(
                    priority=SignalPriority.DAILY,
                    symbol=sym,
                    side=side,
                    strategy="trending_filler",
                    reason=f"{mover.symbol} 24h:{mover.change_24h:+.1f}% vol:${mover.volume_24h / 1e6:.0f}M"
                    f" (best available)",
                    strength=min(0.65, strength),
                    leverage=5,
                    max_age_seconds=7200,
                    source="monitor",
                ),
            )
            existing_syms.add(sym)
            added += 1

        if added < needed:
            for sym in self._major_symbols:
                if added >= needed:
                    break
                if sym in existing_syms:
                    continue
                direction = snap.preferred_direction
                if direction not in ("long", "short"):
                    direction = "long" if snap.fear_greed < 50 else "short"

                self._propose(
                    q,
                    TradeProposal(
                        priority=SignalPriority.DAILY,
                        symbol=sym,
                        side=direction,
                        strategy="major_filler",
                        reason=f"{sym} regime={snap.regime} F&G={snap.fear_greed} (best available major)",
                        strength=0.35,
                        leverage=5,
                        max_age_seconds=7200,
                        source="monitor",
                    ),
                )
                existing_syms.add(sym)
                added += 1

    # ------------------------------------------------------------------
    # Technical Analysis (hub-side strategy execution)
    # ------------------------------------------------------------------

    _STRATEGY_BOT_TARGETS: dict[str, str] = {
        "rsi": "indicators,momentum",
        "macd": "indicators,momentum",
        "bollinger": "indicators,momentum",
        "mean_reversion": "meanrev",
        "compound_momentum": "momentum,extreme",
        "market_open_volatility": "momentum,extreme",
        "swing_opportunity": "swing",
        "grid": "swing",
    }

    async def generate_technical_signals(
        self,
        candidates: list[str],
        fetcher: CandleFetcher,
        queue: TradeQueue,
        strategies: list[str] | None = None,
    ) -> TradeQueue:
        """Run technical analysis strategies on candidate symbols centrally.

        This replaces the per-bot strategy execution loop (old bot.py step 12).
        The hub fetches candles once and runs all strategies, producing
        TradeProposal objects tagged with target bot types.

        Args:
            candidates: Symbols to analyze (e.g. ["BTC/USDT", "ETH/USDT"])
            fetcher: CandleFetcher for market data
            queue: TradeQueue to add proposals to
            strategies: Which strategies to run (None = all built-in)
        """
        import asyncio

        from core.models import SignalAction
        from strategies import BUILTIN_STRATEGIES

        strat_classes = BUILTIN_STRATEGIES
        if strategies:
            strat_classes = {k: v for k, v in strat_classes.items() if k in strategies}

        if not strat_classes or not candidates:
            return queue

        mkt = self._preferred_market_type
        analyzed = 0

        for symbol in candidates:
            if not self._symbol_tradeable(symbol):
                continue
            if not fetcher.has_symbol(symbol):
                continue

            candles = await fetcher.fetch_candles(symbol, "1m", limit=200)
            if len(candles) < 30:
                continue

            ticker = await fetcher.fetch_ticker(symbol)
            await asyncio.sleep(0)

            for strat_name, strat_cls in strat_classes.items():
                try:
                    instance = strat_cls(symbol=symbol, market_type=mkt, leverage=10)
                    for c in candles:
                        instance.feed_candle(c)

                    sig = instance.analyze(candles, ticker)
                    if not sig:
                        continue
                    if sig.action not in (SignalAction.BUY, SignalAction.SELL):
                        continue

                    side = "long" if sig.action == SignalAction.BUY else "short"
                    is_quick = sig.quick_trade
                    priority = SignalPriority.CRITICAL if is_quick else SignalPriority.DAILY
                    if strat_name == "swing_opportunity":
                        priority = SignalPriority.SWING

                    target_bots = self._STRATEGY_BOT_TARGETS.get(strat_name, "momentum")

                    self._propose(
                        queue,
                        TradeProposal(
                            priority=priority,
                            symbol=symbol,
                            side=side,
                            strategy=f"ta_{strat_name}",
                            reason=sig.reason[:200] if sig.reason else f"{strat_name} signal on {symbol}",
                            strength=sig.strength,
                            market_type=sig.market_type,
                            leverage=sig.leverage,
                            quick_trade=is_quick,
                            max_hold_minutes=sig.max_hold_minutes or 0,
                            max_age_seconds=14400 if priority == SignalPriority.DAILY else 300,
                            tick_urgency=sig.tick_urgency.value,
                            target_bot=target_bots,
                            source="hub_ta",
                        ),
                    )
                    analyzed += 1
                except Exception as e:
                    logger.warning("TA {} on {} failed: {}", strat_name, symbol, e)

        if analyzed:
            logger.info("Technical analysis: {} signals from {} candidates", analyzed, len(candidates))
        return queue

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _route_target(proposal: TradeProposal) -> str:
        """Determine which bot style should handle this proposal."""
        if proposal.priority == SignalPriority.SWING:
            return "swing"
        return "momentum"

    def _propose(self, queue: TradeQueue, proposal: TradeProposal) -> None:
        """Add proposal if not on cooldown and not a live duplicate.

        Applies analytics strength modifier before queuing — underperforming
        strategies get progressively weaker signals.
        """
        if not self._symbol_tradeable(proposal.symbol):
            # Keep this at debug while we stabilize symbol hygiene end-to-end.
            # If filtering stays clean, we can remove this log entirely.
            logger.debug("Skipping {}: not on any known exchange", proposal.symbol)
            return

        if self._rejection_cooldown_active(proposal.symbol, proposal.strategy):
            return

        if not proposal.target_bot:
            proposal.target_bot = self._route_target(proposal)
        if proposal.market_type == "futures" and self._preferred_market_type != "futures":
            proposal.market_type = self._preferred_market_type

        proposal.supported_exchanges = self._supported_exchanges(proposal.symbol)

        # Apply analytics modifier to strength
        raw_strength = proposal.strength
        modifier = self._analytics_strength_modifier(proposal.strategy, proposal.symbol, is_quick=proposal.quick_trade)
        cex_modifier = self._cex_strength_modifier(proposal)
        openclaw_modifier = self._openclaw_strength_modifier(proposal)
        proposal.strength = round(raw_strength * modifier * cex_modifier * openclaw_modifier, 4)

        key = f"{proposal.priority.value}_{proposal.symbol}_{proposal.strategy}"

        if key in self._recent_ids:
            cooldown = self._cooldown_seconds[proposal.priority]
            elapsed = (datetime.now(UTC) - self._recent_ids[key]).total_seconds()
            if elapsed < cooldown:
                return

        for ex in queue.get_actionable(proposal.priority):
            if ex.symbol == proposal.symbol and ex.strategy == proposal.strategy:
                return

        queue.add(proposal)
        self._recent_ids[key] = datetime.now(UTC)
        all_ex = set(self._exchange_symbols.keys()) if self._exchange_symbols else set()
        missing = sorted(all_ex - set(proposal.supported_exchanges))
        exchange_note = f" (not on: {', '.join(missing)})" if missing else ""
        analytics_note = f" [analytics: {modifier:.2f}x]" if modifier != 1.0 else ""
        cex_note = f" [cex: {cex_modifier:.2f}x]" if cex_modifier != 1.0 else ""
        openclaw_note = f" [openclaw: {openclaw_modifier:.2f}x]" if openclaw_modifier != 1.0 else ""
        logger.info(
            "QUEUE [{}] {} {} — {} (str={:.2f}){}{}{}{}",
            proposal.priority.value.upper(),
            proposal.side.upper(),
            proposal.symbol,
            proposal.reason,
            proposal.strength,
            analytics_note,
            cex_note,
            openclaw_note,
            exchange_note,
        )

    def _purge_cooldowns(self) -> None:
        cutoff = datetime.now(UTC) - timedelta(hours=24)
        self._recent_ids = {k: v for k, v in self._recent_ids.items() if v > cutoff}

    def _merge_trending(self, snap: IntelSnapshot) -> list[TrendingSnapshot]:
        """Deduplicate trending coins from all sources."""
        seen: set[str] = set()
        result: list[TrendingSnapshot] = []
        for coin in snap.hot_movers + snap.cmc_trending + snap.coingecko_trending:
            key = self._symbol_key(coin.symbol)
            if key not in seen:
                seen.add(key)
                result.append(coin)
        return result

    def _build_cex_symbol_state(self, snap: IntelSnapshot) -> dict[str, dict[str, float]]:
        out: dict[str, dict[str, float]] = {}
        for mover in snap.hot_movers:
            if mover.source != "binance_scanner":
                continue
            key = self._symbol_key(mover.symbol)
            out[key] = {
                "confidence": mover.cex_confidence,
                "vol_accel": mover.cex_vol_accel,
                "score": mover.cex_score,
                "chg_1m": mover.cex_change_1m,
                "chg_5m": mover.change_5m,
                "chg_1h": mover.change_1h,
                "chg_4h": mover.cex_change_4h,
                "chg_1d": mover.cex_change_1d,
                "chg_1w": mover.cex_change_1w,
            }
        return out

    @staticmethod
    def _clamp(value: float, lo: float, hi: float) -> float:
        return max(lo, min(hi, value))

    def _cex_strength_modifier(self, proposal: TradeProposal) -> float:
        apply_cex = True if proposal.strategy.startswith("ta_") else proposal.strategy in self._CEX_TREND_STRATEGIES
        if not apply_cex:
            return 1.0

        st = self._cex_symbol_state.get(self._symbol_key(proposal.symbol))
        if not st:
            return 1.0

        # Confidence acts as a base scalar: low history = mild de-prioritization,
        # mature history = moderate boost.
        confidence = self._clamp(st.get("confidence", 0.0), 0.0, 1.2)
        confidence_mod = 0.75 + 0.5 * confidence

        # Volume acceleration above its own rolling baseline boosts urgency.
        vol_accel = st.get("vol_accel", 1.0)
        vol_mod = 1.0 + self._clamp((vol_accel - 1.0) * 0.25, -0.15, 0.20)

        side_sign = 1.0 if proposal.side == "long" else -1.0
        signed_trend = 0.0
        signed_trend += side_sign * st.get("chg_5m", 0.0) * 0.30
        signed_trend += side_sign * st.get("chg_1h", 0.0) * 0.45
        signed_trend += side_sign * st.get("chg_4h", 0.0) * 0.25
        trend_mod = 1.0 + self._clamp(signed_trend / 20.0, -0.20, 0.25)
        # Strongly opposite multi-horizon momentum should suppress trend-following
        # entries even if confidence/volume are high.
        misalign_penalty = 1.0 + self._clamp(signed_trend / 10.0, -0.45, 0.0)

        score_mod = 1.0 + self._clamp(st.get("score", 0.0) / 25.0, 0.0, 0.15)

        return self._clamp(confidence_mod * vol_mod * trend_mod * score_mod * misalign_penalty, 0.60, 1.50)

    def _openclaw_strength_modifier(self, proposal: TradeProposal) -> float:
        """Apply advisory-only OpenClaw soft weighting.

        OpenClaw never creates trades directly. This only nudges proposal
        strength based on regime/sentiment commentary already merged into
        the hub IntelSnapshot.
        """
        snap = self._openclaw_snapshot
        if snap is None:
            return 1.0

        regime = (snap.openclaw_regime or "unknown").lower()
        confidence = self._clamp(float(snap.openclaw_regime_confidence or 0.0), 0.0, 1.0)
        if regime == "unknown" or confidence <= 0:
            return 1.0

        side_sign = 1.0 if proposal.side == "long" else -1.0
        mod = 1.0

        # Regime directional tilt (small, confidence-weighted)
        regime_bias = 0.12 * confidence
        if regime == "risk_on":
            mod *= 1.0 + (regime_bias * side_sign)
        elif regime in {"risk_off", "caution"}:
            mod *= 1.0 - (regime_bias * side_sign)

        # Sentiment score uses 0-100 scale centered at 50.
        sentiment = self._clamp(float(snap.openclaw_sentiment_score or 50), 0.0, 100.0)
        sentiment_centered = (sentiment - 50.0) / 50.0  # [-1, 1]
        mod *= 1.0 + (0.10 * confidence * sentiment_centered * side_sign)

        # Long/short ratio contrarian nudge to avoid crowded side.
        lsr = float(snap.openclaw_long_short_ratio or 0.0)
        if lsr > 1.15:
            mod *= 0.95 if proposal.side == "long" else 1.05
        elif 0 < lsr < 0.85:
            mod *= 1.05 if proposal.side == "long" else 0.95

        # If OpenClaw explicitly mentions symbol+side, give a mild confidence boost.
        symbol = self._pair_symbol(proposal.symbol)
        for idea in snap.openclaw_idea_briefs[:10]:
            idea_symbol = self._pair_symbol(str(idea.get("symbol", "")))
            if idea_symbol != symbol:
                continue
            idea_side = str(idea.get("side", "neutral")).lower()
            idea_conf = self._clamp(float(idea.get("confidence", 0.0) or 0.0), 0.0, 1.0)
            if idea_side == proposal.side:
                mod *= 1.0 + (0.08 * idea_conf)
            elif idea_side in {"long", "short"}:
                mod *= 1.0 - (0.08 * idea_conf)
            break

        return self._clamp(mod, 0.75, 1.25)

    @staticmethod
    def _pair_symbol(symbol: str) -> str:
        raw = (symbol or "").upper().split(":")[0]
        if "/" in raw:
            return raw
        if raw.endswith("USDT") and len(raw) > 4:
            return f"{raw[:-4]}/USDT"
        if raw.endswith("USD") and len(raw) > 3:
            return f"{raw[:-3]}/USD"
        return f"{raw}/USDT"

    @classmethod
    def _symbol_key(cls, symbol: str) -> str:
        pair = cls._pair_symbol(symbol)
        return pair.split("/", 1)[0]

    def _count_directional_agreement(self, snap: IntelSnapshot) -> int:
        """Count how many independent intel sources agree on the preferred direction."""
        target = snap.preferred_direction
        if target == "neutral":
            return 0

        count = 0
        if snap.fear_greed_bias == target:
            count += 1
        if snap.liquidation_bias == target:
            count += 1
        if snap.whale_bias == target:
            count += 1
        if snap.tv_btc_consensus == target:
            count += 1
        if snap.regime == "risk_on" and target == "long":
            count += 1
        if snap.regime == "risk_off" and target == "short":
            count += 1
        return count

    def _get_tv_analysis(self, snap: IntelSnapshot, symbol: str):
        for tv in snap.tv_analyses:
            if tv.symbol == symbol and tv.interval == "1h":
                return tv
        return None
