#!/usr/bin/env bash
set -euo pipefail

# Build runtime secrets env files from local .env source-of-truth.
#
# Usage:
#   ./scripts/materialize_runtime_secrets.sh local
#   ./scripts/materialize_runtime_secrets.sh prod
#
# Output:
#   env/local.runtime.secrets.env or env/prod.runtime.secrets.env

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:-}"
SOURCE_ENV="$ROOT/.env"

if [[ "$MODE" != "local" && "$MODE" != "prod" ]]; then
  echo "Usage: $0 {local|prod}"
  exit 1
fi

if [[ ! -f "$SOURCE_ENV" ]]; then
  echo "ERROR: missing $SOURCE_ENV"
  exit 1
fi

if [[ "$MODE" == "local" ]]; then
  RUNTIME_ENV="$ROOT/env/local.runtime.env"
  OUTPUT_ENV="$ROOT/env/local.runtime.secrets.env"
  SRC_SUFFIX="TEST"
else
  RUNTIME_ENV="$ROOT/env/prod.runtime.env"
  OUTPUT_ENV="$ROOT/env/prod.runtime.secrets.env"
  SRC_SUFFIX="PROD"
fi

if [[ ! -f "$RUNTIME_ENV" && "$MODE" == "prod" && -f "$ROOT/env/prod.runtime.env.example" ]]; then
  RUNTIME_ENV="$ROOT/env/prod.runtime.env.example"
fi

if [[ ! -f "$RUNTIME_ENV" && "$MODE" == "local" ]]; then
  echo "ERROR: missing $RUNTIME_ENV"
  exit 1
fi

read_kv() {
  local key="$1"
  local value
  value="$(python3 - "$SOURCE_ENV" "$key" <<'PY'
import sys
from pathlib import Path
env_file = Path(sys.argv[1])
target = sys.argv[2]
value = ""
for line in env_file.read_text().splitlines():
    s = line.strip()
    if not s or s.startswith("#") or "=" not in s:
        continue
    k, v = s.split("=", 1)
    if k.strip() == target:
        value = v.strip()
        break
print(value)
PY
)"
  printf "%s" "$value"
}

read_runtime_exchange() {
  python3 - "$RUNTIME_ENV" <<'PY'
import sys
from pathlib import Path
p = Path(sys.argv[1])
exchange = ""
for line in p.read_text().splitlines():
    s = line.strip()
    if not s or s.startswith("#") or "=" not in s:
        continue
    k, v = s.split("=", 1)
    if k.strip() == "EXCHANGE":
        exchange = v.strip().lower()
        break
print(exchange)
PY
}

mask4() {
  local v="$1"
  if [[ -z "$v" ]]; then
    printf "MISSING"
  else
    printf "***%s" "${v: -4}"
  fi
}

selected_exchange=""
if [[ -f "$RUNTIME_ENV" ]]; then
  selected_exchange="$(read_runtime_exchange)"
fi
if [[ -z "$selected_exchange" ]]; then
  if [[ "$MODE" == "prod" ]]; then
    selected_exchange="binance"
  else
    echo "ERROR: EXCHANGE is not set in $RUNTIME_ENV"
    exit 1
  fi
fi

selected_base="$selected_exchange"
if [[ "$selected_base" == binance* ]]; then
  selected_base="binance"
elif [[ "$selected_base" == bybit* ]]; then
  selected_base="bybit"
fi

binance_key="$(read_kv "BINANCE_${SRC_SUFFIX}_API_KEY")"
binance_secret="$(read_kv "BINANCE_${SRC_SUFFIX}_API_SECRET")"
bybit_key="$(read_kv "BYBIT_${SRC_SUFFIX}_API_KEY")"
bybit_secret="$(read_kv "BYBIT_${SRC_SUFFIX}_API_SECRET")"

if [[ "$selected_base" == "binance" ]]; then
  if [[ -z "$binance_key" || -z "$binance_secret" ]]; then
    echo "ERROR: Missing BINANCE_${SRC_SUFFIX}_API_KEY/SECRET in $SOURCE_ENV for mode=$MODE"
    exit 1
  fi
elif [[ "$selected_base" == "bybit" ]]; then
  if [[ -z "$bybit_key" || -z "$bybit_secret" ]]; then
    echo "ERROR: Missing BYBIT_${SRC_SUFFIX}_API_KEY/SECRET in $SOURCE_ENV for mode=$MODE"
    exit 1
  fi
fi

{
  echo "# Auto-generated by scripts/materialize_runtime_secrets.sh ($MODE)"
  echo "# Do not commit. Source: .env (${SRC_SUFFIX} keys)"
  echo "BINANCE_API_KEY=$binance_key"
  echo "BINANCE_API_SECRET=$binance_secret"
  echo "BYBIT_API_KEY=$bybit_key"
  echo "BYBIT_API_SECRET=$bybit_secret"
} > "$OUTPUT_ENV"

chmod 600 "$OUTPUT_ENV" || true

echo "Generated: $OUTPUT_ENV"
echo "EXCHANGE(base): $selected_base"
echo "BINANCE_API_KEY=$(mask4 "$binance_key")"
echo "BINANCE_API_SECRET=$(mask4 "$binance_secret")"
echo "BYBIT_API_KEY=$(mask4 "$bybit_key")"
echo "BYBIT_API_SECRET=$(mask4 "$bybit_secret")"
